<?php

namespace Database\Seeders\Central;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class LeadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        // 1. LIMPA A TABELA ANTES DE INSERIR NOVOS DADOS
        // Resolve o erro de "Duplicate entry".
        DB::table('leads')->truncate();

        // Array para rastrear emails já inseridos (proteção extra para a lista)
        $emailsInseridos = [];

        // Dados da planilha, mapeados para a chave 'cidade'
        $leads = [
            ['cidade' => 'Além Paraíba', 'nome' => 'David da Paz Silveira Teixeira', 'email' => 'ouvidoriacmap@gmail.com', 'telefone' => '(32) 3466-2600'],
            ['cidade' => 'Estrela Dalva', 'nome' => 'Cristian Carvalho Antunes', 'email' => 'gabinete@camaraestreladalva.mg.gov.br', 'telefone' => '(32) 3464-1216'],
            ['cidade' => 'Pirapetinga', 'nome' => 'Anderson. Messias Pacheco', 'email' => 'secretaria@camaradepirapetinga.mg.gov.br', 'telefone' => '32) 3465-2480 ou 3465-1532'],
            ['cidade' => 'Santo Antônio do Aventureiro', 'nome' => 'Maciel Rodrigues', 'email' => 'camarasaaventureiro@yahoo.com.br', 'telefone' => '(32) 3286-1146'],
            ['cidade' => 'Volta Grande', 'nome' => 'Anderson Meneguiti Pereira', 'email' => 'cmvoltagrande@hotmail.com', 'telefone' => '032 - 3463-1380'],
            ['cidade' => 'Almenara', 'nome' => 'AILTON FERREIRA DE OLIVEIRA', 'email' => 'cm.almenara@hotmail.com', 'telefone' => '(33)3721-1281'],
            ['cidade' => 'Bandeira', 'nome' => 'Genivaldo Félix Gonçalves', 'email' => 'contato@camarabandeira.mg.gov.br', 'telefone' => '(33) 3728-1157'],
            ['cidade' => 'Felisburgo', 'nome' => 'Edmário Dias da Rocha', 'email' => 'contato@camarafelizburgo.mg.gov.br', 'telefone' => '(33) 3743-1280'],
            ['cidade' => 'Jacinto', 'nome' => 'Nilson Quaresma Dias', 'email' => 'atendimento@dominio.leg.br', 'telefone' => '(33) 3723-1717'],
            ['cidade' => 'Jequitinhonha', 'nome' => 'Gilson De Oliveira Silva', 'email' => 'contato@camarajequitinhonha.mg.gov.br', 'telefone' => '(33) 3741-1420'],
            ['cidade' => 'Joaíma', 'nome' => 'Junior Narck Rodrigues De Almeida', 'email' => 'cmjoaima@live.com', 'telefone' => '33374515000'],
            ['cidade' => 'Jordânia', 'nome' => 'Marcos Ramos', 'email' => 'camara@jordania.mg.gov.br', 'telefone' => '(33) 3726-1120'],
            ['cidade' => 'Mata Verde', 'nome' => 'José Ricardo Gonçalves da Silva', 'email' => 'pmmv@mataverde.mg.gov.br', 'telefone' => '(33) 3722-1687 ou (33) 3722-1511'],
            ['cidade' => 'Palmópolis', 'nome' => 'Alexandre Pereira Da Rocha', 'email' => 'camarampalmopolis@hotmail.com', 'telefone' => '(33) 3744 9102'],
            ['cidade' => 'Rio do Prado', 'nome' => 'GILSON GUIMARÃES FIGUEIREDO', 'email' => 'gilson@camarariodoprado.mg.gov.br', 'telefone' => null],
            ['cidade' => 'Rubim', 'nome' => 'Gervasio Fernandes', 'email' => 'camaramunicipalderubim@gmail.com', 'telefone' => null],
            ['cidade' => 'Salto da Divisa', 'nome' => 'Valdeci Beltrão de Oliveira', 'email' => 'contato@camarasaltodadivisa.mg.gov.br', 'telefone' => '(33) 3725-1151'],
            ['cidade' => 'Santa Maria do Salto', 'nome' => 'Sergio Gomes da Silva', 'email' => 'cmsantamariadosa@yahoo.com.br', 'telefone' => null],
            ['cidade' => 'Santo Antônio do Jacinto', 'nome' => 'Zenóbio Pereira Queiroz', 'email' => 'zenobiopq@hotmailcom', 'telefone' => null],
            ['cidade' => 'Alfredo Vasconcelos', 'nome' => 'EDEVALDO SÓCRATES DA SILVA', 'email' => 'contato@camaraalfredovasconcelos.mg.gov.br', 'telefone' => null],
            ['cidade' => 'Alto Rio Doce', 'nome' => 'Ari Sant ana de carvalho', 'email' => 'camaramunicipal@altoriodoce.mg.leg.br', 'telefone' => null],
            ['cidade' => 'Antônio Carlos', 'nome' => 'RAFAEL CAMPOS FERNANDES', 'email' => 'cac@antoniocarlos.mg.leg.br', 'telefone' => null],
            ['cidade' => 'Barbacena', 'nome' => 'Amarílio Augusto de Andrade', 'email' => 'camaramunicipal@barbacena.mg.gov.br', 'telefone' => '(32) 99128-0374'],
            ['cidade' => 'Capela Nova', 'nome' => 'LUCIANO BARBOSA DE SOUZA', 'email' => 'atendimento@capelanova.org.com.br', 'telefone' => '(31) 3727-1101'],
            ['cidade' => 'Carandaí', 'nome' => 'PEDRO MARCONI DE SOUZA RODRIGUES', 'email' => 'contato@camaracarandai.mg.gov.br', 'telefone' => null],
            ['cidade' => 'Cipotânea', 'nome' => 'Divanil Dos Santos Moreira', 'email' => 'contato@cipotanea.mg.gov.br', 'telefone' => '(32) 999184521'],
            ['cidade' => 'Desterro do Melo', 'nome' => 'Luiz Henrique de Castro', 'email' => 'luizhenriquedecastro@gmail.com', 'telefone' => '(32) 98493-0350'],
            ['cidade' => 'Ibertioga', 'nome' => 'Cazeca', 'email' => 'cmibertioga@gmail.com', 'telefone' => '(32) 93618-0203'],
            ['cidade' => 'Paiva', 'nome' => 'Francisco de Assis Maurício', 'email' => 'camarapaiva@outlook.com', 'telefone' => null],
            ['cidade' => 'Ressaquinha', 'nome' => 'Marcus Vinicius de Moura Bernardo', 'email' => 'contato@camaraderessaquinha.mg.gov.br', 'telefone' => null],
            ['cidade' => 'Santa Bárbara do Tugúrio', 'nome' => 'ivaney leandro nepomuceno', 'email' => 'camarasbtugurio@yahoo.com.br', 'telefone' => '(32) 3365-1467'],
            ['cidade' => 'Santa Rita de Ibitipoca', 'nome' => 'Eduardo Alisson da Fonseca', 'email' => 'camara@santaritadeibitipoca.cam.mg.gov.br', 'telefone' => null],
            ['cidade' => 'Santana do Garambéu', 'nome' => 'Mário Dimas Fagundes de Castro', 'email' => 'camaragarambeu@gmail.com', 'telefone' => '(32)99822-6905'],
            ['cidade' => 'Senhora dos Remédios', 'nome' => 'Marcos Roberto Milagres de Assis', 'email' => 'camaramunicipalsdr@gmail.com', 'telefone' => null],
            ['cidade' => 'Caiana', 'nome' => 'Luciano Toledo Fernandes', 'email' => 'cmcaiana@hotmail.com', 'telefone' => null],
            ['cidade' => 'Caparaó', 'nome' => 'RENAN BATISTA GONÇALVES', 'email' => 'contato@camaradecaparao.mg.gov.br', 'telefone' => '(32) 3747-1076'],
            ['cidade' => 'Carangola', 'nome' => 'Luciano Amaral de Souza', 'email' => 'camara@camaracarangola.mg.gov.br', 'telefone' => '(32) 3741-1970'],
            ['cidade' => 'Divino', 'nome' => 'Divino Augusto de Oliveira', 'email' => 'camara.divino2@gmail.com', 'telefone' => '(32) 3743-1452'],
            ['cidade' => 'Espera Feliz', 'nome' => 'Matusalém Marques de Oliveira', 'email' => 'matusalem@esperafeliz.mg.leg.br', 'telefone' => '(32) 3746-1562'],
            ['cidade' => 'Faria Lemos', 'nome' => 'Neide Vieira da Silva', 'email' => 'contato@camarafarialemos.mg.gov.br', 'telefone' => '(32) 3749-1230'],
            ['cidade' => 'Fervedouro', 'nome' => 'Fábio Junior Correia', 'email' => 'presidencia@camarafervedouro.mg.gov.br', 'telefone' => '(32) 3742-1313'],
            ['cidade' => 'Orizânia', 'nome' => 'Felix Dias Ferreira', 'email' => null, 'telefone' => '(32) 3743 7166'],
            ['cidade' => 'Pedra Bonita', 'nome' => 'FERNANDO JOAQUIM DA COSTA', 'email' => 'camarapedrabonita@yahoo.com', 'telefone' => '(31) 3872-9106'],
            ['cidade' => 'Pedra Dourada', 'nome' => 'José Heleno Martins', 'email' => 'ouvidoria@cmpedradourada.mg.gov.br', 'telefone' => '(32) 3748-1045'],
            ['cidade' => 'Tombos', 'nome' => 'SIDNEI OLIVEIRA DA SILVA', 'email' => 'recepcao@camaratombos.mg.gov.br', 'telefone' => '(32) 3751-2214 (32) 3751-1164'],
            ['cidade' => 'Bom Jesus do Galho', 'nome' => 'MOISES DIAS RASPANTE', 'email' => 'camaramunicipalbjg@hotmail.com', 'telefone' => '(33) 3354-1451'],
            ['cidade' => 'Caratinga', 'nome' => 'Cleider Costa de Medeiros', 'email' => 'camara@cmcaratinga.mg.gov.br', 'telefone' => '(33) 3329-9000'],
            ['cidade' => 'Entre Folhas', 'nome' => 'ARILDO ROBERTO DE PAIVA', 'email' => 'contato@cmentrefolhas.mg.gov.br', 'telefone' => '(33) 3324-6197'],
            ['cidade' => 'Imbé de Minas', 'nome' => 'WALDEIR BARBOSA RIBEIRO', 'email' => 'gabinete@cmimbedeminas.mg.gov.br', 'telefone' => '33 8836-0670 (33) 99811-4783'],
            ['cidade' => 'Inhapim', 'nome' => 'Afonso Carlos Vieira', 'email' => null, 'telefone' => null],
            ['cidade' => 'Piedade de Caratinga', 'nome' => 'RONALDO ADRIANO DE ALMEIDA', 'email' => 'gabinete@cmpiedadedecaratinga.mg.gov.br', 'telefone' => '(33) 3323-8100'],
            ['cidade' => 'Santa Bárbara do Leste', 'nome' => 'Êni Edes Marcelo Lopes', 'email' => 'contato@camarasbl.mg.gov.br', 'telefone' => '(33) 3326-1096'],
            ['cidade' => 'Santa Rita de Minas', 'nome' => 'Juliana Aparecida Costa Silva', 'email' => 'camaramunicipalsrm@gmail.com', 'telefone' => '(33) 3326-6052'],
            ['cidade' => 'São Domingos das Dores', 'nome' => 'Marcos Martins de Paiva', 'email' => 'ouvidoria@camarasaodomingosdasdores.mg.gov.br', 'telefone' => '(33) 3315-8408'],
            ['cidade' => 'São Sebastião do Anta', 'nome' => null, 'email' => 'contato@cmsaosebastiaodoanta.mg.gov.br', 'telefone' => '(33) 3315-7050'],
            ['cidade' => 'Ubaporanga', 'nome' => 'Júlio César Machado dos Santos', 'email' => 'camaramunicipalubaporanga@gmail.com', 'telefone' => '(33) 3323-1500'],
            ['cidade' => 'Vargem Alegre', 'nome' => 'Nicodemos Machado Campos', 'email' => 'secretaria@cmva.mg.gov.b', 'telefone' => '(33 )3324-1146'],
            ['cidade' => 'Vermelho Novo', 'nome' => 'Warley Alves de Lima', 'email' => 'camara@camvermelhonovo.mg.gov.br', 'telefone' => '(33) 3351-8100'],
            ['cidade' => 'Caranaíba', 'nome' => 'ADEMIR FERNANDES DA SILVA', 'email' => 'camara@caranaiba.mg.gov.br', 'telefone' => '(31) 98364-7926'],
            ['cidade' => 'Casa Grande', 'nome' => 'Andréia Guilhermina Vieira da Conceição', 'email' => 'atendimento@camaracasagrande.mg.gov.br', 'telefone' => '(31) 93618-1332'],
            ['cidade' => 'Catas Altas da Noruega', 'nome' => 'Edmilson de Souza Rodrigues', 'email' => 'atendimento@camaracatasaltasdanoruega.mg.gov.br', 'telefone' => '3137521288'],
            ['cidade' => 'Conselheiro Lafaiete', 'nome' => 'Washington Fernando Bandeira', 'email' => 'camara@conselheirolafaiete.mg.leg.br', 'telefone' => '(31) 3769-8100'],
            ['cidade' => 'Cristiano Otoni', 'nome' => 'Marciana Elisângela Pereira', 'email' => 'adm@cristianootoni.cam.mg.gov.br', 'telefone' => '(31) 98271-6591'],
            ['cidade' => 'Itaverava', 'nome' => 'RONE AZEVEDO ROBERTO', 'email' => 'administrativo@camaraitaverava.mg.gov.br', 'telefone' => '(31) 99675-7346'],
            ['cidade' => 'Lamim', 'nome' => 'Jean Luiz Da Silva', 'email' => 'cmlamim@gmail.com', 'telefone' => '3137541341'],
            ['cidade' => 'Piranga', 'nome' => 'Antônio Carlos de Oliveira', 'email' => 'pirangacamarasecretaria@gmail.com', 'telefone' => '(31) 3746-1879'],
            ['cidade' => 'Queluzito', 'nome' => 'LIDIANE VIEIRA DE SOUZA', 'email' => 'camara@camaraqueluzito.mg.gov.br', 'telefone' => '(31) 3722-1247'],
            ['cidade' => 'Rio Espera', 'nome' => 'Ana Paula Pinto da Silva', 'email' => 'crioespera@gmail.com', 'telefone' => '(31) 983464182'],
            ['cidade' => 'Santana dos Montes', 'nome' => null, 'email' => 'contato@camarasantanadosmontes.mg.gov.br', 'telefone' => '(31) 3726-1139'],
            ['cidade' => 'Senhora de Oliveira', 'nome' => 'Silvério Silva Moreira', 'email' => 'silverio.silva@camarasenhoradeoliveira.mg.gov.br', 'telefone' => '31 3812-0904'],
            ['cidade' => 'Carmésia', 'nome' => 'Rayane do Carmo Pereira Souza', 'email' => 'contato@carmesia.cam.mg.gov.br', 'telefone' => '(31) 3864-1394'],
            ['cidade' => 'Dom Joaquim', 'nome' => 'Iedo Lúcio De Fátima Teixeira', 'email' => 'diretoria@camaradj.com.br', 'telefone' => '(031) 3866 1269'],
            ['cidade' => 'Dores de Guanhães', 'nome' => 'José Geraldo Monteiro', 'email' => 'contato@camaradoresdeguanhaes.mg.gov.br', 'telefone' => '(33) 3426-1349'],
            ['cidade' => 'Guanhães', 'nome' => 'Mauro da Conceição Neves', 'email' => 'maurocaneconeves@gmail.com', 'telefone' => '(33) 3421 4451 — (33) 3421 2870'],
            ['cidade' => 'Materlândia', 'nome' => 'GAUDÊNCIO VENTURA DA CRUZ', 'email' => null, 'telefone' => '33 – 99829-2782'],
            ['cidade' => 'Rio Vermelho', 'nome' => 'daniel francisco de souza', 'email' => 'secretaria@camaraderiovermelho.mg.gov.br', 'telefone' => '(33) 9963-6380'],
            ['cidade' => 'Sabinópolis', 'nome' => 'Denis Henrique Filardete de Pinho', 'email' => 'sabilegislativo@yahoo.com.br', 'telefone' => '33 3423-1031 33 3423-1180'],
            ['cidade' => 'Senhora do Porto', 'nome' => 'Wenderson Pires Figueiredo', 'email' => 'camarasporto@yahoo.com.br', 'telefone' => '(33) 3424-1368'],
            ['cidade' => 'Virginópolis', 'nome' => 'Juliano Alberto de Araújo', 'email' => 'contato@virginopolis.cam.mg.gov.br', 'telefone' => '(33) 3416-1252'],
            ['cidade' => 'Água Boa', 'nome' => 'Elenita Alves Xavier Barreiros', 'email' => 'elenita-xavier@hotmail.com', 'telefone' => null],
            ['cidade' => 'Aimorés', 'nome' => 'WAGNER FERREIRA DE OLIVEIRA KNOBLAUCH', 'email' => 'wagner@gwlegis.com.br', 'telefone' => null],
            ['cidade' => 'Alpercata', 'nome' => 'FIORIVALDO NATAL PITOL', 'email' => 'secretaria@camaraalpercata.mg.gov.br', 'telefone' => '033 34020100'],
            ['cidade' => 'Alvarenga', 'nome' => 'KAUAN SOUZA RODRIGUES', 'email' => 'contato@camaraalvarenga.mg.gov.br', 'telefone' => '(33) 3328-1151'],
            ['cidade' => 'Capitão Andrade', 'nome' => 'LUCIMAR FERNANDES DE OLIVEIRA', 'email' => 'cmcapandrade@yahoo.com.br', 'telefone' => '(33) 3231-9122'],
            ['cidade' => 'Central de Minas', 'nome' => 'Miris Antônio dos Reis', 'email' => 'contato@camaracm.mg.gov.br', 'telefone' => '(33) 3243-1372'],
            ['cidade' => 'Conselheiro Pena', 'nome' => 'Vinícius Tápias', 'email' => 'cvcpena@hotmail.com', 'telefone' => '(33) 3261-2510'],
            ['cidade' => 'Coroaci', 'nome' => 'Ana Luiza Moura de Oliveira', 'email' => 'AnaLuiza@gwlegis.com.br', 'telefone' => '(33) 3291-1227'],
            ['cidade' => 'Cuparaque', 'nome' => 'VANUZA RODRIGUES MAINETTI', 'email' => 'contato@camaracuparaque.mg.gov.br', 'telefone' => '(33) 3262-5160'],
            ['cidade' => 'Divino das Laranjeiras', 'nome' => 'Elziane Amaral', 'email' => 'contato@camaradivinodaslaranjeiras.mg.gov.br', 'telefone' => '(33) 3245-1140'],
            ['cidade' => 'Divinolândia de Minas', 'nome' => 'Osvanio Ferreira dos Santos', 'email' => 'camaradivinolandia@yahoo.com.br', 'telefone' => '(33) 3414-1132'],
            ['cidade' => 'Engenheiro Caldas', 'nome' => 'Romilda Aparecida Pereira Silva', 'email' => 'camara@engenheirocaldas.mg.gov.br', 'telefone' => '(33) 3234-1185'],
            ['cidade' => 'Fernandes Tourinho', 'nome' => 'Luzia Reis de Souza', 'email' => null, 'telefone' => '(33) 3237-1118 zap'],
            ['cidade' => 'Frei Inocêncio', 'nome' => 'Thiago Abdul Khalek', 'email' => 'camarafreiinocencio@gwlegis.com.br', 'telefone' => '(33) 3284-1384'],
            ['cidade' => 'Galiléia', 'nome' => 'JOSÉ GERALDO BOARETO SANTOS', 'email' => 'jose@gwlegis.com.br', 'telefone' => '(33) 3244-1235'],
            ['cidade' => 'Goiabeira', 'nome' => null, 'email' => null, 'telefone' => '(33) 3262-1363'],
            ['cidade' => 'Gonzaga', 'nome' => 'Marcio Souza Borges', 'email' => 'contato@camaragonzaga.mg.gov.br', 'telefone' => '(33) 3415-1232 / 33-98404-5546'],
            ['cidade' => 'Governador Valadares', 'nome' => 'Alessandro Ferraz', 'email' => 'comunicacao@camaragv.mg.gov.br', 'telefone' => '(33) 3272-2506'],
            ['cidade' => 'Itabirinha', 'nome' => 'Gilvan Neres de Souza', 'email' => 'contato@camaraitabirinha.mg.gov.br', 'telefone' => '(33) 9844-7526'],
            ['cidade' => 'Itanhomi', 'nome' => 'Valdir Dias Belicio', 'email' => 'valdirbelicio@hotmail.com', 'telefone' => '(33) 988384440 / (33) 99908-3554'],
            ['cidade' => 'Itueta', 'nome' => 'ARNALDO KAMKE', 'email' => 'ver.arnaldokamke@itueta.mg.leg.br', 'telefone' => '(33) 3266-3175'],
            ['cidade' => 'Jampruca', 'nome' => 'Antônio Caetano Dos Reis', 'email' => 'contato@camarajampruca.mg.gov.br', 'telefone' => '(33) 3513-9205'],
            ['cidade' => 'José Raydan', 'nome' => 'Heuller Mariano Goncalves', 'email' => 'contato@camarajoseraydan.mg.gov.br', 'telefone' => '(33) 3431-9052'],
            ['cidade' => 'Mantena', 'nome' => 'Wadson Said de Carvalho', 'email' => 'controladoria@camaramantena.mg.gov.br', 'telefone' => '(33) 9 9982-7960'],
            ['cidade' => 'Marilac', 'nome' => 'Darlene Maia', 'email' => 'darlene@gwlegis.com.br', 'telefone' => '(33) 3292-1580'],
            ['cidade' => 'Mathias Lobato', 'nome' => 'Alexandre Ferreira de Morais Neto', 'email' => 'cmmathiaslobato@hotmail.com', 'telefone' => '(33) 3284-1426'],
            ['cidade' => 'Mendes Pimentel', 'nome' => 'ELIENE ALVES SIMÕES', 'email' => 'eliane@gwlegis.com.br', 'telefone' => '(33) 3246-1279'],
            ['cidade' => 'Nacip Raydan', 'nome' => null, 'email' => 'contato@camaranacipraydan.mg.gov.br', 'telefone' => '(33) 9979-1199'],
            ['cidade' => 'Nova Belém', 'nome' => 'MASCARINO HONORATO GOMES', 'email' => 'mascarino@gwlegis.com.br', 'telefone' => '(33) 3241-8001'],
            ['cidade' => 'Resplendor', 'nome' => 'Francisco Dimas de Assis', 'email' => 'ver.dimasassis@camararesplendor.mg.gov.br', 'telefone' => '(33) 3263-2043'],
            ['cidade' => 'Santa Efigênia de Minas', 'nome' => 'Marcio Aires Fernandes', 'email' => 'contato@camarasantaefigeniademinas.mg.gov.br', 'telefone' => '(33) 3297-1306'],
            ['cidade' => 'Santa Maria do Suaçuí', 'nome' => 'Adriano Duarte de Oliveira Rocha', 'email' => 'camaramsms17@gmail.com', 'telefone' => '33) 3431-1443'],
            ['cidade' => 'Santa Rita do Itueto', 'nome' => 'LUIZ CARLOS SALDANHA', 'email' => 'camarasri@gmail.com', 'telefone' => '(33) 3265-1200'],
            ['cidade' => 'São Félix de Minas', 'nome' => 'Antônio Batista da Silva', 'email' => 'contato@saofelixdeminas.cam.mg.gov.br', 'telefone' => '(33) 3246-9061'],
            ['cidade' => 'São Geraldo da Piedade', 'nome' => 'Waldiomar Rodrigues Santiago Nascimento', 'email' => 'contato@cmsaogeraldodapiedade.mg.gov.br', 'telefone' => '(33) ) 3238-1246'],
            ['cidade' => 'São Geraldo do Baixio', 'nome' => 'WARLEI ARTUR DE SOUZA SERVINO', 'email' => 'camaramunicipalsgb@gmail.com', 'telefone' => '(33) 3244-8020'],
            ['cidade' => 'São João do Manteninha', 'nome' => 'José Caetano', 'email' => 'contato@saojoaodomanteninha.cam.mg.gov.br', 'telefone' => '(33) 3242-1312'],
            ['cidade' => 'São José da Safira', 'nome' => 'Alaerci Giovanella Silva', 'email' => 'secretaria@camarasaojosedasafira.mg.gov.br', 'telefone' => '(33) 9 9858-4942 / (33) 9 9941-8378'],
            ['cidade' => 'São Sebastião do Maranhão', 'nome' => 'Pedro Nazare Campos', 'email' => 'Pedro@gwlegis.com.br', 'telefone' => '(33) 3432-1379'],
            ['cidade' => 'Sardoá', 'nome' => 'NOE PEREIRA DE BRITO', 'email' => 'contato@camarasardoa.mg.gov.br', 'telefone' => '(33) 3296-1181'],
            ['cidade' => 'Sobrália', 'nome' => 'Rúsvel Rocha Neto', 'email' => 'camara@camarasobralia.mg.gov.br', 'telefone' => '(33) 3232-1325'],
            ['cidade' => 'Tarumirim', 'nome' => 'Zé Pedro', 'email' => 'contato@cmtarumirim.mg.gov.br', 'telefone' => '(33) 3233-1134'],
            ['cidade' => 'Tumiritinga', 'nome' => 'Ivani Miranda de Faria', 'email' => 'secretaria@camaratumiritinga.mg.gov.br', 'telefone' => '(33) 8808-7764'],
            ['cidade' => 'Virgolândia', 'nome' => 'Fernando Eduarte Bessa', 'email' => 'camara@virgolandia.mg.leg.br', 'telefone' => '(33) 3295-1593'],
            ['cidade' => 'Açucena', 'nome' => 'Raimundo Giovani Maciel', 'email' => 'contato@camaracamaraacucena.mg.gov.br', 'telefone' => '(33) 3298-1225'],
            ['cidade' => 'Belo Oriente', 'nome' => 'Waldir Mendes da Silva', 'email' => null, 'telefone' => '31) 3258-1941'],
            ['cidade' => 'Braúnas', 'nome' => 'GILMAR MARQUES FERREIRA', 'email' => 'ouvidoria@camarabraunas.mg.gov.br', 'telefone' => '(33) 3425-1123.'],
            ['cidade' => 'Bugre', 'nome' => 'Cleomar de Fátima Monteiro Laureano', 'email' => null, 'telefone' => '(33) 3355-8011'],
            ['cidade' => 'Dom Cavati', 'nome' => 'Eduardo de Freitas', 'email' => 'camaramunicipal2017dc@hotmail.com', 'telefone' => '(33) 99869-1341'],
            ['cidade' => 'Iapu', 'nome' => 'Altair Assis Rodrigues', 'email' => 'contato@camaradeiapu.mg.gov.br', 'telefone' => '(33) 3355-1194'],
            ['cidade' => 'Ipaba', 'nome' => 'Valter Inácio', 'email' => null, 'telefone' => '(31) 3823-1631'],
            ['cidade' => 'Ipatinga', 'nome' => 'Werley Glicério Furbino de Araújo', 'email' => 'vereadorley@gmail.com', 'telefone' => '(31) 3829-1214'],
            ['cidade' => 'Joanésia', 'nome' => 'DIEGO HENRIQUE FERNANDES DA CUNHA', 'email' => 'diego@gwlegis.com', 'telefone' => '(33) 3252-1400'],
            ['cidade' => 'Mesquita', 'nome' => 'TIAGO ASSIS DE OLIVEIRA', 'email' => 'tiagoassis251081@hotmail.com', 'telefone' => '(33) 3251-1316 / (33) 99115-6169'],
            ['cidade' => 'Naque', 'nome' => 'ADEMIR CAETANO MATIAS', 'email' => null, 'telefone' => '(33) 3403-0790'],
            ['cidade' => 'Periquito', 'nome' => 'RODRIGO MARTINS DE SOUZA', 'email' => 'rodrigo@gwlegis.com', 'telefone' => '(33) 3322-9540'],
            ['cidade' => 'Santana do Paraíso', 'nome' => 'César Roberto de Deus', 'email' => 'secretaria@santanadoparaiso.mg.leg.br', 'telefone' => '31 2942-9300 / +55 31 3251-6341 / 31 3251-6338'],
            ['cidade' => 'São João do Oriente', 'nome' => null, 'email' => 'admin.sjo@saojoaodooriente.mg.gov.br', 'telefone' => '(33) 99844-0518'],
            ['cidade' => 'Barão de Cocais', 'nome' => 'Barão de Cocais', 'email' => 'contato@cmbaraodecocais.mg.gov.br', 'telefone' => '(31) 3837-1391'],
            ['cidade' => 'Bom Jesus do Amparo', 'nome' => 'Joaquim Aparecido dos Santos', 'email' => 'camarabjamparo@outlook.com', 'telefone' => '(31) 3833-1204'],
            ['cidade' => 'Catas Altas', 'nome' => 'Anizio Nazareno Aparecido', 'email' => 'anizio.vereador@camaracatasaltas.mg.gov.br', 'telefone' => '(31) 93618-0792'],
            ['cidade' => 'Ferros', 'nome' => 'JONARA GONÇALVES SILVA', 'email' => 'jonara@gwlegis.com.br', 'telefone' => '(31) 3863-1420'],
            ['cidade' => 'Itabira', 'nome' => 'Carlos Henrique Silva Filho', 'email' => 'carlin.filho@itabira.cam.mg.gov.br', 'telefone' => '(31) 3839-1500'],
            ['cidade' => 'Itambé do Mato Dentro', 'nome' => 'José Nonato Ferreira', 'email' => 'ouvidoria@camaraitambedomatodentro.mg.gov.br', 'telefone' => '(31) 3836-5265'],
            ['cidade' => 'Morro do Pilar', 'nome' => 'ADEMIR DE OLIVEIRA VIEIRA', 'email' => 'adm@morrodopilar.cam.mg.gov.br', 'telefone' => '(31) 3866-5491'],
            ['cidade' => 'Passabém', 'nome' => null, 'email' => 'contato@camarapassabem.mg.gov.br', 'telefone' => '(31) 3836-1200'],
            ['cidade' => 'Santa Bárbara', 'nome' => 'Márcio Rodrigues Pedro', 'email' => 'assessoria.comunicacao@santabarbara.cam.mg.gov.br', 'telefone' => '(31) 3832-1631'],
            ['cidade' => 'Santa Maria de Itabira', 'nome' => 'JAIR LINO DE CARVALHO LAGE', 'email' => 'camarasantamaria@gmail.com', 'telefone' => '( 31) 3838-1290'],
            ['cidade' => 'Santo Antônio do Rio Abaixo', 'nome' => 'Santo Antônio do Rio Abaixo', 'email' => 'cmsara2014@yahoo.com.br', 'telefone' => '(31) 3867-1155'],
            ['cidade' => 'São Gonçalo do Rio Abaixo', 'nome' => 'Marlon Tulio', 'email' => 'marlontulio@camarasaogoncalo.mg.gov.br', 'telefone' => '(31) 3833-5202'],
            ['cidade' => 'São Sebastião do Rio Preto', 'nome' => 'Jerry Adriano da Silva', 'email' => 'contato@camarasaosebastiaodoriopreto.mg.gov.br', 'telefone' => '(31) 3867-5117'],
            ['cidade' => 'Andrelândia', 'nome' => 'Ligia Landim', 'email' => 'contato@camaradeandrelandia.mg.gov.br', 'telefone' => '(35) 3325-1121'],
            ['cidade' => 'Aracitaba', 'nome' => 'Jorge Raimundo Rezende', 'email' => 'camaraaracitabamg@yahoo.com.br', 'telefone' => '(32)3256-1186'],
            ['cidade' => 'Arantina', 'nome' => 'Maria Aparecida de Almeida Oliveira', 'email' => 'administracao@camaraarantina.mg.gov.br', 'telefone' => '(32) 3296-1329'],
            ['cidade' => 'Belmiro Braga', 'nome' => 'RODRIGO DE LANES BENTO', 'email' => 'camarabelmirobragasite@gmail.com', 'telefone' => '(32) 3284-1203'],
            ['cidade' => 'Bias Fortes', 'nome' => 'JEFFERSON VICTOR REIS PINTO', 'email' => 'contato@camarabiasfortes.mg.gov.br', 'telefone' => '(32) 3344-1323'],
            ['cidade' => 'Bicas', 'nome' => 'Isaias Pereira Lima', 'email' => 'camara@bicas.mg.leg.br', 'telefone' => '(32) 3271-2973'],
            ['cidade' => 'Bocaina de Minas', 'nome' => 'Tânia Vani Bemfica', 'email' => 'contato@camarabocainademinas.mg.gov.br', 'telefone' => '(32) 3294-1386'],
            ['cidade' => 'Bom Jardim de Minas', 'nome' => 'Reinaldo Ribeiro Nunes', 'email' => 'camara@bomjardimdeminas.mg.leg.br', 'telefone' => '+55 32 3292-1421'],
            ['cidade' => 'Chácara', 'nome' => 'Bruno Fernandes de Morais', 'email' => 'secretaria.cam.chacara@gmail.com', 'telefone' => '+55 32 3277-1015'],
            ['cidade' => 'Chiador', 'nome' => 'GUSTAVO MARQUES DE ALMEIDA', 'email' => 'gustavomarquesalmeida1984@gmail.com', 'telefone' => '(32) 9 8457-0684 / (32) 3285-1219'],
            ['cidade' => 'Coronel Pacheco', 'nome' => 'Rafael Alberto Mourão', 'email' => 'secretaria@coronelpacheco.cam.mg.gov.br', 'telefone' => '(32) 3258 – 1208'],
            ['cidade' => 'Descoberto', 'nome' => 'Odair José do Nascimento', 'email' => 'cmdescoberto@yahoo.com.br', 'telefone' => '(32)3265-1258'],
            ['cidade' => 'Ewbank da Câmara', 'nome' => 'Elizete Maria de Souza', 'email' => null, 'telefone' => '(32)3255-1173'],
            ['cidade' => 'Goianá', 'nome' => 'Paulo Dib "Pelinha"', 'email' => 'camara@goiana.mg.leg.br', 'telefone' => '(32) 3274-5301'],
            ['cidade' => 'Guarará', 'nome' => 'Helivelton Araújo Silvas', 'email' => null, 'telefone' => '(32) 3264-1413'],
            ['cidade' => 'Juiz de Fora', 'nome' => 'José Márcio Lopes Guedes', 'email' => 'cidadao@camarajf.mg.gov.br', 'telefone' => '32 3313 4700'],
            ['cidade' => 'Liberdade', 'nome' => 'Luiz Antônio Lamim', 'email' => 'ouvidoria@camaraliberdade.mg.gov.br', 'telefone' => '(32) 3293-1119'],
            ['cidade' => 'Lima Duarte', 'nome' => 'FABIO PEREIRA VIEIRA', 'email' => 'fabiodarocadeira@limaduarte.mg.leg.br', 'telefone' => '(32) 98855-1782'],
            ['cidade' => 'Mar de Espanha', 'nome' => 'Rafael garcia furtado', 'email' => 'camara@mardeespanha.mg.leg.br', 'telefone' => '(32) 3490-0252'],
            ['cidade' => 'Maripá de Minas', 'nome' => 'Marco Aurélio de Souza', 'email' => 'tvcmmaripa@gmail.com', 'telefone' => '(32)98408-9581'],
            ['cidade' => 'Matias Barbosa', 'nome' => 'Sônia Maria Vieira da Cunha Pinheiro', 'email' => 'diretoria@matiasbarbosa.mg.leg.br', 'telefone' => '(32) 3273-5722'],
            ['cidade' => 'Olaria', 'nome' => 'iago batista campos de oliveira', 'email' => 'camaramunicipaldeolaria@yahoo.com.br', 'telefone' => '+55 32 3288-1138'],
            ['cidade' => 'Oliveira Fortes', 'nome' => 'Osmar Cabral', 'email' => 'camaraoliveirafortes@gmail.com', 'telefone' => '(32) 3366-1133'],
            ['cidade' => 'Passa-Vinte', 'nome' => 'Magno Faisther de Souza', 'email' => 'camarapassavinte@hotmail.com', 'telefone' => '32 3295-1178'],
            ['cidade' => 'Pedro Teixeira', 'nome' => 'marcelo aparecido gomes', 'email' => 'camara@pedroteixeira.cam.mg.gov.br', 'telefone' => '(32) 3282-1178'],
            ['cidade' => 'Pequeri', 'nome' => 'Cleydson Silva Ângelo', 'email' => 'camara.pequeri@gmail.com', 'telefone' => '0800 032 1828'],
            ['cidade' => 'Piau', 'nome' => 'Emiliano Resende de Carvalho', 'email' => 'camaramunicipaldepiau@yahoo.com.br', 'telefone' => '(32) 3254-1131'],
            ['cidade' => 'Rio Novo', 'nome' => 'Sebastião José Esperança', 'email' => 'contato@camararionovo.mg.gov.br', 'telefone' => '32 3274 1132 / 32 3274 2212'],
            ['cidade' => 'Rio Preto', 'nome' => 'CELSO MACHADO FERREIRA', 'email' => 'celso@cmrp.mg.gov.br', 'telefone' => '(32) 3283-1394'],
            ['cidade' => 'Rochedo de Minas', 'nome' => 'jose geraldo de mendonça', 'email' => null, 'telefone' => '0800-010-0333'],
            ['cidade' => 'Santa Bárbara do Monte Verde', 'nome' => 'Luiz Carlos Machado', 'email' => 'camara.sbmv@yahoo.com.br', 'telefone' => '(32) 3283-8113'],
            ['cidade' => 'Santa Rita de Jacutinga', 'nome' => 'Marco Ângelo', 'email' => 'camaramunicipalsrj2025@gmail.com', 'telefone' => '(32) 3567-0040'],
            ['cidade' => 'Santana do Deserto', 'nome' => 'Luiz Carlos Florentino de Souza', 'email' => 'vereadorluiz@santanadodeserto.mg.leg.br', 'telefone' => '+55 32 3112-3168'],
            ['cidade' => 'Santos Dumont', 'nome' => 'Sebastião Antônio da Silva', 'email' => 'contato@camarasd.mg.gov.b', 'telefone' => '(32) 3252-9600'],
            ['cidade' => 'São João Nepomuceno', 'nome' => 'ELUZA SALVADOR CÔRTES', 'email' => 'contato@camarasjn.mg.gov.br', 'telefone' => '32 3261-1107'],
            ['cidade' => 'Senador Cortes', 'nome' => 'Francisco França do Carmo e Suely Medeiros do Carmo', 'email' => null, 'telefone' => '(32) 3287-1187'],
            ['cidade' => 'Simão Pereira', 'nome' => 'Mauro Luciano Matias', 'email' => 'camsimaopereira@outlook.com', 'telefone' => '(32) 2028-5025'],
            ['cidade' => 'Bela Vista de Minas', 'nome' => 'Aldrin Laje de Oliveira', 'email' => 'camarabela.vista.mg@gmail.com', 'telefone' => '(31) 3853-1288'],
            ['cidade' => 'João Monlevade', 'nome' => 'Fernando Linhares Pereira', 'email' => 'fernandolinhares@joaomonlevade.mg.leg.br', 'telefone' => '(31) 3852-3524'],
            ['cidade' => 'Nova Era', 'nome' => 'RONALDO DIAS DE ANDRADE', 'email' => null, 'telefone' => '(31) 3861-1300'],
            ['cidade' => 'Rio Piracicaba', 'nome' => 'Aleksandro José da Silva', 'email' => 'camararp@camararp.mg.gov.br', 'telefone' => '(31) 3854-1353'],
            ['cidade' => 'São Domingos do Prata', 'nome' => 'Marcos Augusto Mendes Braga', 'email' => 'camara@saodomingosdoprata.mg.leg.br', 'telefone' => '+55 31 3856-1578'],
            ['cidade' => 'Argirita', 'nome' => 'Marcio Muniz Alves', 'email' => 'camara@argirita.mg.leg.br', 'telefone' => '(32) 3449-7708'],
            ['cidade' => 'Astolfo Dutra', 'nome' => 'CLEMILson ALVES NEIVA', 'email' => 'presidente@astolfodutra.mg.leg.br', 'telefone' => '(32) 3458-0901'],
            ['cidade' => 'Cataguases', 'nome' => 'Vinicius Machado Costa de Oliveira', 'email' => 'presidenciacamara36@gmail.com', 'telefone' => '(32) 3429-1929'],
            ['cidade' => 'Dona Eusébia', 'nome' => 'CARLOS VAGNER GOMES', 'email' => 'cmde@outlook.com', 'telefone' => '(32) 99837-1353'],
            ['cidade' => 'Itamarati de Minas', 'nome' => 'Júber Célio Barbosa Rodrigues', 'email' => 'camaraitamarati@gmail.com', 'telefone' => '(32) 3452-1556'],
            ['cidade' => 'Laranjal', 'nome' => 'Geraldo Ilson de Matos', 'email' => 'camara@camaralaranjal.mg.gov.b', 'telefone' => '(32) 3424-1248'],
            ['cidade' => 'Leopoldina', 'nome' => 'Bernardo Junqueira e Renó Guedes', 'email' => 'imprensa@leopoldina.mg.leg.br', 'telefone' => '(32) 3449-7570'],
            ['cidade' => 'Palma', 'nome' => 'RONIE HUNGRIA DE PAULA', 'email' => 'contato@camarapalma.mg.gov.br', 'telefone' => '(32) 3446-1450'],
            ['cidade' => 'Recreio', 'nome' => 'Paulo Henrique Ferreira da Silva', 'email' => 'camara@recreio.mg.leg.br', 'telefone' => '(32) 3444-1507 / (32) 3444-1671'],
            ['cidade' => 'Santana de Cataguases', 'nome' => 'Rafaela Vieira de Souza', 'email' => 'camarasantanadecataguases@gmail.com', 'telefone' => '(32) 34251-2520'],
            ['cidade' => 'Abre Campo', 'nome' => 'Raimundo Célio de Paiva', 'email' => 'camarasec@camaraabrecampo.mg.gov.br', 'telefone' => '(31) 3872-1200'],
            ['cidade' => 'Alto Caparaó', 'nome' => 'RICARDO FIGUEIREDO EMERICH', 'email' => 'ccaparao@yahoo.com.br', 'telefone' => '(32) 3747-2639 / 3747-2697'],
            ['cidade' => 'Alto Jequitibá', 'nome' => 'JOSÉ AMÉRICO TASMO BASTOS', 'email' => 'cmaltojequitiba@yahoo.com.br', 'telefone' => '(33) 3343-1144'],
            ['cidade' => 'Caputira', 'nome' => 'Horácio Carvalho de Souza', 'email' => 'camara@caputira.mg.leg.br', 'telefone' => '+55 (31)3873-5102'],
            ['cidade' => 'Chalé', 'nome' => 'Alaor Antônio Anacleto', 'email' => 'ouvidoria@cmchale.mg.gov.br', 'telefone' => '(33) 3345-1277'],
            ['cidade' => 'Conceição de Ipanema', 'nome' => 'Emerson Alves Aleixo', 'email' => 'secretaria@cmci.mg.gov.br', 'telefone' => null],
            ['cidade' => 'Durandé', 'nome' => 'Sirlei Guerra Paiva', 'email' => 'dcamaramunicipal@yahoo.com', 'telefone' => '+55 33 33421124'],
            ['cidade' => 'Ipanema', 'nome' => 'ALEX RODRIGUES CARDOSO', 'email' => 'secretaria@ipanema.mg.leg.br', 'telefone' => '+55 33 3314-1982'],
            ['cidade' => 'Lajinha', 'nome' => 'JULIO DA SILVA HASTENRREITER', 'email' => 'contato@lajinha.mg.leg.br', 'telefone' => '(33) 984255412 (33) 3344-1558'],
            ['cidade' => 'Luisburgo', 'nome' => 'SIDONIL SINDRA', 'email' => 'cmluisburgo@yahoo.com.br', 'telefone' => '(33) 99704-3718'],
            ['cidade' => 'Manhuaçu', 'nome' => 'Rose Mary Miranda Dornelas', 'email' => 'secretaria@manhuacu.mg.leg.br', 'telefone' => '(33) 3331-1740'],
            ['cidade' => 'Manhumirim', 'nome' => 'Alexandre de Jesus Nascimento', 'email' => 'xandinho@manhumirim.mg.leg.br', 'telefone' => '3399119-1476'],
            ['cidade' => 'Martins Soares', 'nome' => 'FELIPE RODRIGUES FILHO', 'email' => 'camara@cmmartinssoares.mg.gov.br', 'telefone' => '(33) 3342-2001'],
            ['cidade' => 'Matipó', 'nome' => 'WANDERSON DIOGO RICARDO', 'email' => 'ouvidoria@camaramatipo.mg.gov.br', 'telefone' => '(31) 3873-1164'],
            ['cidade' => 'Mutum', 'nome' => 'NAESTE GOMES DA SILVA', 'email' => 'falecom@camaramutum.mg.gov.br', 'telefone' => '(33) 3312-1212'],
            ['cidade' => 'Pocrane', 'nome' => 'Márcia Vargas de Faria', 'email' => 'ouvidoria@cmpocrane.mg.gov.br', 'telefone' => '(33) 3316-1310'],
            ['cidade' => 'Reduto', 'nome' => 'FRANCISCO MENDES TEIXEIRA', 'email' => 'secretaria@camarareduto.mg.gov.br', 'telefone' => '(33) 3378-4171'],
            ['cidade' => 'Santa Margarida', 'nome' => 'noe celestino dos santos', 'email' => 'vereador.noe@santamargarida.mg.leg.br', 'telefone' => '38751199'],
            ['cidade' => 'Santana do Manhuaçu', 'nome' => 'ARILSON DE SOUZA MAGALHÃES', 'email' => 'camaramunicipaldesantana@gmail.com', 'telefone' => '(33) 3463-0211'],
            ['cidade' => 'São João do Manhuaçu', 'nome' => 'LUCILENE ORNELAS DA SILVA SANTOS', 'email' => 'administrativo@camarasjmanhuacu.mg.gov.br', 'telefone' => '(33) 3377-1148'],
            ['cidade' => 'São José do Mantimento', 'nome' => 'ADEMAR SALES LACERDA', 'email' => 'cmmantimento@gmail.com', 'telefone' => '(33) 3335-1120'],
            ['cidade' => 'Simonésia', 'nome' => 'DÁVILA BRUNA DUTRA DA SILVA BAIA', 'email' => 'cmsimonesia@yahoo.com.br', 'telefone' => '(33) 3336-1370'],
            ['cidade' => 'Taparuba', 'nome' => 'SILVANEY ANTONIO DIAS', 'email' => 'ouvidoria@camarataparuba.mg.gov.br', 'telefone' => '(33) 3314-8010'],
            ['cidade' => 'Antônio Prado de Minas', 'nome' => 'CARLOS ALBERTO DE FREITAS TÓFANI', 'email' => 'cmpradodeminas@hotmail.com', 'telefone' => '(32) 3725-1009'],
            ['cidade' => 'Barão de Monte Alto', 'nome' => 'Rogério Henrique Pereira', 'email' => 'camara.barao@yahoo.com.br', 'telefone' => '(32) 3727-1016'],
            ['cidade' => 'Eugenópolis', 'nome' => 'RONAN JOSÉ SIMÕES LOPES', 'email' => 'atendimento@cmeugenopolis.mg.gov.br', 'telefone' => '32 3724-1690'],
            ['cidade' => 'Miradouro', 'nome' => 'Ailton Fernando de Aredes', 'email' => 'atendimento.camaramiradouro@gmail.com', 'telefone' => '(32) 3753-1188'],
            ['cidade' => 'Miraí', 'nome' => 'GESIANO INACIO', 'email' => 'camaramunicipaldemirai@gmail.com', 'telefone' => '(32) 3426-1260'],
            ['cidade' => 'Muriaé', 'nome' => 'Evandro Maciel da Silva', 'email' => 'cmm@camaramuriae.mg.gov.br', 'telefone' => '32 3696-3050'],
            ['cidade' => 'Patrocínio do Muriaé', 'nome' => 'RONALDO PEREIRA DA SILVA', 'email' => 'camara@cmpatrociniodomuriae.mg.gov.br', 'telefone' => '(32) 3726-1279'],
            ['cidade' => 'Rosário da Limeira', 'nome' => 'ANDREZA LUZIA DE SOUZA ALVES', 'email' => 'camararosariodalimeira@gmail.com', 'telefone' => '(32) 3507-0001'],
            ['cidade' => 'São Francisco do Glória', 'nome' => 'Hugo Stterfferson Cunha', 'email' => 'secretaria@saofranciscodogloria.mg.leg.br', 'telefone' => '(32) 3754-1485'],
            ['cidade' => 'São Sebastião da Vargem Alegre', 'nome' => 'joao batista breno junior', 'email' => 'cmssva@saosebastiaodavargemalegre.mg.leg.br', 'telefone' => '(32) 3519-0003'],
            ['cidade' => 'Vieiras', 'nome' => 'LEANDRO BELINATO PEREIRA', 'email' => 'camara@vieiras.mg.leg.br', 'telefone' => '(32) 3755-1082'],
            ['cidade' => 'Itabirito', 'nome' => 'marcio antonio de oliveira junior', 'email' => 'marcio.junior@itabirito.mg.leg.br', 'telefone' => '(31) 3561-1599'],
            ['cidade' => 'Mariana', 'nome' => 'EDIRALDO ARLINDO DE FREITAS RAMOS', 'email' => 'ediraldoramos_vereador@yahoo.com.br', 'telefone' => '(31) 3558-1360'],
            ['cidade' => 'Ouro Preto', 'nome' => 'vantuir antonio da silva', 'email' => 'contato@cmop.mg.gov.br', 'telefone' => '(31) 3552-8500 (31) 3552-8515'],
            ['cidade' => 'Acaiaca', 'nome' => 'JOÃO PAULO ARAÚJO', 'email' => 'legislativoacaiaca@gmail.com', 'telefone' => '(31) 3887-1239'],
            ['cidade' => 'Alvinópolis', 'nome' => 'JOSÉ AGOSTINHO PONTES', 'email' => 'camaraalvinopolis@hotmail.com', 'telefone' => '31 3855-1463 | 31 3855-1091 | 31 97131-6763'],
            ['cidade' => 'Amparo do Serra', 'nome' => 'Cleidson Ribeiro Botelho Miquelino', 'email' => 'sic@camaraamparodoserra.mg.gov.br', 'telefone' => '(31) 3895-5119'],
            ['cidade' => 'Barra Longa', 'nome' => 'Greison Anderson de Souza da Costa', 'email' => 'secretaria@camaradebarralonga.mg.gov.br', 'telefone' => '(31) 98319-8218'],
            ['cidade' => 'Diogo de Vasconcelos', 'nome' => 'ODETE BARBOSA PINTO DE OLIVEIRA', 'email' => 'odete@camaradiogodevasconcelos.mg.gov.br', 'telefone' => '(31) - 38861283'],
            ['cidade' => 'Dom Silvério', 'nome' => 'ALEX EVANGELISTA COELHO', 'email' => 'camaradomsilveriomg@gmail.com', 'telefone' => '(31) 3857-1312'],
            ['cidade' => 'Guaraciaba', 'nome' => 'Silvério Cândido Gaudêncio', 'email' => 'camara@guaraciaba.mg.leg.br', 'telefone' => '(31) 3893-5591'],
            ['cidade' => 'Jequeri', 'nome' => 'jose moura da silva', 'email' => 'camarajequeri@hotmail.com', 'telefone' => '(31) 3877-1512'],
            ['cidade' => 'Oratórios', 'nome' => 'Vinicius de Castro Bragione', 'email' => 'cmoratorios@hotmail.com', 'telefone' => '(31) 3876-9119'],
            ['cidade' => 'Piedade de Ponte Nova', 'nome' => 'Flávio Magalhães da Cruz', 'email' => 'camaramunicipalpiedadedepontenova@hotmail.com', 'telefone' => '+55 31 3871-2110'],
            ['cidade' => 'Ponte Nova', 'nome' => 'Wellington Sabino de Oliveira', 'email' => 'camara@pontenova.mg.leg.br', 'telefone' => '+55 31 3819-3251'],
            ['cidade' => 'Raul Soares', 'nome' => 'Ewerton Gualberto de Souza', 'email' => 'secretaria@cmraulsoares.mg.gov.br', 'telefone' => '(33) 3351 2090'],
            ['cidade' => 'Rio Casca', 'nome' => 'Marcia da Conceição Marques', 'email' => 'camarariocasca@yahoo.com.br', 'telefone' => '31 3924 0651'],
            ['cidade' => 'Rio Doce', 'nome' => 'Fernando César de Jesus', 'email' => 'camara@riodoce.mg.leg.br', 'telefone' => '(31) 3883-5284'],
            ['cidade' => 'Santa Cruz do Escalvado', 'nome' => 'Ramon Phillipe Xavier dos Santos', 'email' => 'cmsce@yahoo.com.br', 'telefone' => '(31) 3883-1181'],
            ['cidade' => 'Santo Antônio do Grama', 'nome' => 'Geraldo Vitor de Souza', 'email' => 'contato@cmsantoantoniodograma.mg.gov.br', 'telefone' => '(31) 3872-5308'],
            ['cidade' => 'São José do Goiabal', 'nome' => 'Wallace Armelino Rufino', 'email' => 'camara@saojosedogoiabal.mg.leg.br', 'telefone' => null],
            ['cidade' => 'São Pedro dos Ferros', 'nome' => 'CARLA ALESANDRA NAZIARENO', 'email' => 'camspf@yahoo.com.br', 'telefone' => '(33) 3352-1166'],
            ['cidade' => 'Sem-Peixe', 'nome' => 'José da Purificação Vieira', 'email' => 'camaramunicipal@sempeixemg.com.br', 'telefone' => '+55 (31) 98312-9526'],
            ['cidade' => 'Sericita', 'nome' => 'RAIMUNDO VIDOMAR RODRIGUES', 'email' => 'contato@camarasericita.mg.gov.br', 'telefone' => '(31) 3875-5202'],
            ['cidade' => 'Urucânia', 'nome' => 'Dimas Roberto', 'email' => 'contato@camaraurucania.mg.gov.br', 'telefone' => '(31) 3876-1227 / (31) 3876-1520'],
            ['cidade' => 'Barroso', 'nome' => 'Maria Trindade Bedesque Nascimento', 'email' => 'mariadovaltair@camarabarroso.mg.gov.br', 'telefone' => '(32) 99882-6730 / (32) 3359-3040'],
            ['cidade' => 'Bom Sucesso', 'nome' => 'GLEDSON JÚNIO PAIXÃO GONÇALVES', 'email' => 'secretaria@camarabomsucesso.mg.gov.br', 'telefone' => '(35) 3841-1580'],
            ['cidade' => 'Conceição da Barra de Minas', 'nome' => 'Leandro Mauro Resende', 'email' => 'camara@camaracbm.mg.gov.br', 'telefone' => '(32) 3375-1232'],
            ['cidade' => 'Coronel Xavier Chaves', 'nome' => 'Sábatha Resende Chaves Assunção', 'email' => 'contato@camaracxc.mg.gov.br', 'telefone' => '32-3216-1053'],
            ['cidade' => 'Dores de Campos', 'nome' => 'GUILHERME ALVES DE FREITAS', 'email' => 'camaramunicipaldc@gmail.com', 'telefone' => '(32) 3353-1590'],
            ['cidade' => 'Ibituruna', 'nome' => 'Denilson Teixeira', 'email' => 'camara@camaraibituruna.mg.gov.br', 'telefone' => '(35)3498-0248'],
            ['cidade' => 'Lagoa Dourada', 'nome' => 'Ronaldo Maciel Campos', 'email' => 'camaramunicipal@lagoadourada.mg.leg.br', 'telefone' => '(32) 3363-1434'],
            ['cidade' => 'Madre de Deus de Minas', 'nome' => 'Othon José Araújo Fajardo', 'email' => 'secretaria@madrededeusdeminas.cam.mg.gov.br', 'telefone' => '(32) 3338-1594'],
            ['cidade' => 'Nazareno', 'nome' => 'JOÃO NESTOR DE CARVALHO', 'email' => 'camara@camaranazareno.mg.gov.br', 'telefone' => '(35) 99821-3811'],
            ['cidade' => 'Piedade do Rio Grande', 'nome' => 'IAGO LUCINDA TEIXEIRA', 'email' => 'comunicacao@piedadedoriogrande.cam.mg.gov.br', 'telefone' => '(32) 3335-1618'],
            ['cidade' => 'Prados', 'nome' => 'DELFIM GERALDO FERREIRA', 'email' => 'cac@prados.cam.mg.gov.br', 'telefone' => '(32) 3353-6313'],
            ['cidade' => 'Resende Costa', 'nome' => 'José Cláudio de Sousa Resende', 'email' => 'camaramrcosta@mgconecta.com.br', 'telefone' => '(32) 3354-1526'],
            ['cidade' => 'Ritápolis', 'nome' => 'SORMANI JESUS DE OLIVEIRA', 'email' => 'camara@ritapolis.mg.leg.br', 'telefone' => '(32) 3356-1159'],
            ['cidade' => 'Santa Cruz de Minas', 'nome' => 'Marcelo Geraldo da Silva', 'email' => 'camara@santacruzdeminas.mg.gov.br', 'telefone' => '(32) 3373-3743'],
            ['cidade' => 'São João del Rei', 'nome' => 'Everton da Conceição Mendes', 'email' => 'legislativo@camarasaojoaodelrei.mg.gov.br', 'telefone' => '(32) 3379-3150'],
            ['cidade' => 'São Tiago', 'nome' => 'Mariana Lourdes Vieira Silva', 'email' => 'secretaria@camarasaotiago.mg.gov.br', 'telefone' => '(32) 3376-1357'],
            ['cidade' => 'São Vicente de Minas', 'nome' => 'Ariane Guimarães Reis Silva Paulsen', 'email' => 'contato@camarasvm.mg.gov.br', 'telefone' => '(35) 3323-1332'],
            ['cidade' => 'Tiradentes', 'nome' => 'MARCOS ANTÔNIO DA SILVA', 'email' => 'gabinete@camaratiradentes.mg.gov.br', 'telefone' => '(32) 3355-1433 ou (32) 99994-3433'],
            ['cidade' => 'Brás Pires', 'nome' => 'SERGIO DE OLIVEIRA ALVES', 'email' => 'sergio@camarabraspires.mg.gov.br', 'telefone' => '+55 (32) 3534-1167'],
            ['cidade' => 'Coimbra', 'nome' => 'Maciel de Freitas Silva Braga', 'email' => 'camaramunicipaldecoimbramg@gmail.com', 'telefone' => '(32) 98448-2589'],
            ['cidade' => 'Divinésia', 'nome' => 'Roseli de Freitas Ferreira', 'email' => 'secretaria@camaradivinesia.mg.gov.br', 'telefone' => '032 3535-1244'],
            ['cidade' => 'Dores do Turvo', 'nome' => 'MARCÍLIO FRANCO DA MOTA', 'email' => 'camaravereadores2013@hotmail.com', 'telefone' => '(32) 3576-1460'],
            ['cidade' => 'Ervália', 'nome' => 'Johaby de Paula Almeida', 'email' => 'cme-mg@hotmail.com', 'telefone' => '(32) 3554-1873'],
            ['cidade' => 'Guarani', 'nome' => 'William Santos Mendes', 'email' => 'contato@guarani.mg.leg.br', 'telefone' => '(32) 3575-1853'],
            ['cidade' => 'Guidoval', 'nome' => 'Roberto Carlos de Almeida', 'email' => 'contato@guidoval.mg.leg.br', 'telefone' => '+ (55) 032 3578-1405'],
            ['cidade' => 'Guiricema', 'nome' => 'Marcos Antônio Ribeiro Ferraz', 'email' => 'camaradeguiricema@gmail.com', 'telefone' => '+55 032 3553-1165'],
            ['cidade' => 'Mercês', 'nome' => 'Rosimeire das Mercês Costa', 'email' => 'camara@camaramerces.mg.gov.br', 'telefone' => '(32) 3337-1567'],
            ['cidade' => 'Piraúba', 'nome' => 'JOSMAR TOLEDO XAVIER', 'email' => 'contato@pirauba.mg.leg.br', 'telefone' => '(32) 93300-6482'],
            ['cidade' => 'Presidente Bernardes', 'nome' => 'ADEMIR DOS SANTOS BARBOSA', 'email' => 'cmpresidentebernardes@gmail.com', 'telefone' => '(32) 3538-1194'],
            ['cidade' => 'Rio Pomba', 'nome' => 'Ivan Ferreira Martins', 'email' => 'camararp@rdfnet.com.br', 'telefone' => '32 3571-1455'],
            ['cidade' => 'Rodeiro', 'nome' => 'Gilberto Guerra Mendonça', 'email' => 'presidente@rodeiro.mg.leg', 'telefone' => '(32) 3577-1274'],
            ['cidade' => 'São Geraldo', 'nome' => 'Felipe Ferreira Martins', 'email' => 'camarasgmg@gmail.com', 'telefone' => '(32) 3556-1507'],
            ['cidade' => 'Senador Firmino', 'nome' => 'Geraldo Donizetti Lopes', 'email' => 'camaramunicipalsf@gmail.com', 'telefone' => '(32) 3536-1134'],
            ['cidade' => 'Silveirânia', 'nome' => 'Marinaldo Garcia Rego', 'email' => 'camara@silveirania.cam.mg.gov.br', 'telefone' => '(32) 3572-118'],
            ['cidade' => 'Tabuleiro', 'nome' => 'Francisco Ferraz', 'email' => 'camara@tabuleiro.mg.leg.br', 'telefone' => '(32) 99952-8238'],
            ['cidade' => 'Tocantins', 'nome' => 'Washington Luiz Nunes Apolinario', 'email' => 'contato@tocantins.mg.leg.br', 'telefone' => '(32) 3574-1098'],
            ['cidade' => 'Ubá', 'nome' => 'José Maria Fernandes', 'email' => 'comunicacao@uba.mg.leg.br', 'telefone' => '(32) 3539-5000'],
            ['cidade' => 'Visconde do Rio Branco', 'nome' => 'Marinho Jose de Almeida Neto', 'email' => 'vereadormarinho@viscondedoriobranco.mg.leg.br', 'telefone' => '(32) 3551-8000'],
            ['cidade' => 'Araponga', 'nome' => 'Francisco Chagas Abreu', 'email' => 'camaraaraponga@hotmail.com', 'telefone' => '(31)3894-1288'],
            ['cidade' => 'Cajuri', 'nome' => 'Gilmar Lopes de Oliveira', 'email' => 'contato@camaracajuri.mg.gov.br', 'telefone' => '(31) 3898-1252'],
            ['cidade' => 'Canaã', 'nome' => 'Caio Martins Fonseca', 'email' => 'camara@canaa.mg.leg.br', 'telefone' => '(31) 3892 – 1206'],
            ['cidade' => 'Paula Cândido', 'nome' => 'Everaldo Roberto da Conceição', 'email' => 'camarampc@yahoo.com.br', 'telefone' => '+55 32 9908-7136'],
            ['cidade' => 'Pedra do Anta', 'nome' => 'Luciano de Carvalho Abranches', 'email' => 'secretaria@pedradoanta.cam.mg.gov.br', 'telefone' => '031 3896-1197'],
            ['cidade' => 'Porto Firme', 'nome' => 'Carlos Antônio Grigório', 'email' => 'pf.camaramunicipal@gmail.com', 'telefone' => '(31) 3893-1456'],
            ['cidade' => 'São Miguel do Anta', 'nome' => 'Reginaldo Marcio Miranda', 'email' => 'camara@saomigueldoanta.mg.leg.br', 'telefone' => '(31) 3897 – 1279'],
            ['cidade' => 'Teixeiras', 'nome' => 'Julio Cezar Pereira', 'email' => 'camarateixeiras@hotmail.com', 'telefone' => '(31) 3895-1320'],
            ['cidade' => 'Viçosa', 'nome' => 'Robson Alencar De Souza', 'email' => 'robsonsouza@camaravicosa.com.br', 'telefone' => '(31) 3899-7500'],
        ];

        $dataToInsert = [];
        $now = Carbon::now();

        foreach ($leads as $lead) {
            // Pula a linha se o 'nome' OU 'email' estiverem vazios, ou se o email já foi usado
            if (empty($lead['nome']) || empty($lead['email']) || isset($emailsInseridos[$lead['email']])) {
                continue; // Pula para o próximo lead
            }

            // Monta o array para inserção com a nova coluna 'cidade'
            $dataToInsert[] = [
                'nome' => $lead['nome'],
                'email' => $lead['email'],
                'telefone' => $lead['telefone'] ?? null,
                'cidade' => $lead['cidade'], // Usando a nova coluna
                'endereco' => null, // Definindo a coluna antiga como nula
                'site' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ];

            $emailsInseridos[$lead['email']] = true;
        }

        // Insere em lotes para otimizar a performance
        foreach (array_chunk($dataToInsert, 500) as $chunk) {
            DB::table('leads')->insert($chunk);
        }
    }
}
